### ISSUE TITLE
Ability to wait for state execution completion with long polling API

### ISSUE THREAD

**Issue by longquanzheng** [indeedeng/iwf#268]
Something like:
```java
client.WaitForStateExecution(<workflowId>, <StateExecutionId>); // blocking API call until it's completed or timeout
```

This API will start a internal/system workflow , which waits for a signal, and let the state execution to signalWithStart it to complete. The workflowId will be  `__Iwf_system+<runId>+<stateExecutionId>`

the StartWorkflow API will also require to tell what are the state execution will need to be waited, when starting a workflow.

**Comment by longquanzheng** [comment]
Alternatively, wait for a state execution to complete may be even more useful / general to use .

**Comment by longquanzheng** [comment]
https://github.com/indeedeng/iwf/pull/345

**Comment by dennissetiawan** [comment]
Hi @longquanzheng  is this feature already available in golandg sdk? Is there an example for this?

**Comment by longquanzheng** [comment]
> Hi @longquanzheng is this feature already available in golang sdk? Is there an example for this?

It’s only available in Java SDK atm because indeed mostly uses Java SDK. And we use it in production for a while. 

Would you like to make a PR in Golang SDK by following the code in Java? I think it is pretty straightforward forward:

https://github.com/indeedeng/iwf-java-sdk/blob/56ef8d0c11b94b070ceb2bd02a53ea0d8ff0c661/src/main/java/io/iworkflow/core/Client.java#L996
