### ISSUE TITLE
Add healthcheck API

### ISSUE THREAD

**Issue by longquanzheng** [indeedeng/iwf#324]
return format:
```
{
  "condition": "OK", # use constant value
  "hostname": "xxxxxx", # just return the hostname or IP
  "duration": 0  # return zero here is fine. 
}
```

### Note 1
The format is required, because already defined in [here](https://github.com/indeedeng/libhealth#healthcheck-endpoints) and being used broadly at Indeed.

For duration, it means the time to calculate the health of the service in seconds. 

For the first iteration(PR), we can just return zero. 

For the second iteration, we can use Temporal/Cadence service client to perform the healthcheck like this:
```golang
_, err := serviceClient.CheckHealth(ctx, &client.CheckHealthRequest{})
```
and calculate the timeeslapsed of the API call. Because Temporal/Cadence is the only dependency of iWF. 

### Note 2:
We need to define a new API endpoint in the swagger: https://github.com/indeedeng/iwf-idl/blob/main/iwf.yaml#L13 

The endpoint URL should be `GET /info/healthcheck` based on the Indeed standard.

**Comment by Rajan-226** [comment]
@krishnaduttPanchagnula Are you working on this?

**Comment by longquanzheng** [comment]
Thanks @krishnaduttPanchagnula @Rajan-226 for your interests. 

To help you get started, I just added more details to help. LMK if you have any questions.

**Comment by Rajan-226** [comment]
Thanks @longquanzheng, Will pick this up.

**Comment by Rajan-226** [comment]
@longquanzheng Will complete this tomorrow, Can you check the draft once though: https://github.com/indeedeng/iwf/pull/327
